apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, get, *, allow
    p, role:admin, applications, sync, *, allow
    p, role:admin, applications, update, *, allow
    p, role:admin, applications, delete, *, allow
    p, role:admin, clusters, get, *, allow
    g, admin, role:admin
