apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
    - name: metrics
      port: 8082
      targetPort: 8082
