apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chakrellah/k8s-gitops-project.git
    targetRevision: HEAD
    path: charts/grafana
    helm:
      values: |
        service:
          type: NodePort
          port: 80
          nodePort: 32000
          
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
