apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.0
    helm:
      values: |
        controller:
          metrics:
            enabled: true
        repoServer:
          metrics:
            enabled: true
        server:
          metrics:
            enabled: true
          service:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8083"
            ports:
              - name: metrics
                port: 8083
                targetPort: 8083
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
