prometheus:
  server:
    service:
      type: NodePort
      port: 80
      targetPort: 9090
      nodePort: 32001
  alertmanager:
    enabled: true

additionalScrapeConfigs:
  - job_name: 'argocd'
    static_configs:
      - targets: ['argocd-server.argocd.svc.cluster.local:8083']
