apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chakrellah/k8s-gitops-project.git
    targetRevision: HEAD
    path: applications/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
  - path: ../secrets/postgres-secret.yaml       
  - path: ../postgres/app.yaml                  

