apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chakrellah/k8s-gitops-project.git
    targetRevision: feature/argocd-monitoring
    path: applications
    directory:
      recurse: true   #critical to ensure all sub-applications are included
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
