apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/vault-addr: "http://vault.app.svc:8200"
        vault.hashicorp.com/role: "nodejs-api-role"
        vault.hashicorp.com/agent-inject-secret-DATABASE_URL: "kv/data/nodejs-api"
        vault.hashicorp.com/agent-inject-template-DATABASE_URL: |
          {{`{{- with secret "kv/data/nodejs-api" -}}`}}
          export DATABASE_URL="{{`{{ .Data.data.DATABASE_URL }}`}}"
          {{`{{- end }}`}}
    spec:
      serviceAccountName: nodejs-api
      containers:
        - name: nodejs-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          command: ["/bin/sh"]
          args: ["-c", "source /vault/secrets/database_url && node index.js"]

