apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nodejs-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}