enableCustomRBAC: true

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

server:
  metrics:
    enabled: true
  service:
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: metrics
        port: 8082
        targetPort: 8082

applicationSet:
  metrics:
    enabled: true
